 #! /usr/bin/env python
# -*- coding: utf-8 -*-

# Setup

from __future__ import (absolute_import, division,
                        print_function, unicode_literals)
from builtins import *
import pandas as pd
import os
import sys
import re
import gzip
import csv
from collections import defaultdict
from snakemake.utils import min_version
min_version("6.4.1")
from snakemake.exceptions import RuleException

wildcard_constraints:
    runid = 'SRR[0-9]{6,9}', # runid must start with 'SRR', followed by 6-9 digits
    samid = 'SAMN[0-9]{6,9}'  # samid must start with 'GSM', followed by 6-9 digits

# config file
configfile: "config/config.yaml"

with open(config['sample_csv'], 'r') as csvfile:
    dialect = csv.Sniffer().sniff(csvfile.read(1024))
    csvfile.seek(0)
    METADATA = [row for row in csv.DictReader(csvfile)]

SAMPLES = [d[config['colname_SAMPLE']] for d in METADATA]
RUNS = [d[config['colname_RUN']] for d in METADATA]

SAMPLE_RUN = defaultdict(list)
for d in METADATA:
    SAMPLE_RUN[d[config['colname_SAMPLE']]].append(d[config['colname_RUN']])

rule all:
    input:
        expand("results/completed/{samid}_completed.txt", samid=SAMPLES)

# Rules to include
include: "rules/references.smk"
# include: "rules/fasterq_dump.smk"
include: "rules/fasterq_dump_paired.smk"
include: "rules/fastqc.smk"
include: "rules/star_index.smk"
# include: "rules/star_alignment.smk"
include: "rules/star_alignment_paired.smk"
include: "rules/telescope.smk"

# To run single-end files, comment out the paired rules, and uncomment the single. 